package commands

import (
	"fmt"
	"os"
	"strings"
)

// Doc section markers, matching the internal/features README generator so the
// two generated sections behave identically.
const (
	DocBeginMarker = "<!-- BEGIN SLASH COMMANDS -->"
	DocEndMarker   = "<!-- END SLASH COMMANDS -->"
)

// RenderMarkdown renders the VISIBLE commands as markdown, grouped by category.
//
// Generated rather than hand-written because the hand-written table rotted
// exactly the way hand-written tables do: it documented most of the stubs as
// working features and omitted most of the real ones. A table derived from the
// registry cannot say a command exists when it does not, and cannot advertise
// one that is hidden.
func RenderMarkdown(r *Registry) string {
	var b strings.Builder
	b.WriteString(DocBeginMarker)
	b.WriteString("\n<!-- generated by `ycode features commands --write`; do not edit by hand -->\n")

	grouped := r.ListByCategory()
	for _, cat := range Categories(grouped) {
		fmt.Fprintf(&b, "\n### %s\n\n", strings.Title(cat)) //nolint:staticcheck // ASCII category names
		b.WriteString("| Command | Description |\n|---------|-------------|\n")
		for _, s := range grouped[cat] {
			name := "`/" + s.Name + "`"
			if s.Usage != "" {
				name = "`" + s.Usage + "`"
			}
			// A usage string like "/review [commit|staged|branch]" carries a
			// pipe, which is the CELL SEPARATOR — unescaped it silently splits
			// the row into extra columns.
			fmt.Fprintf(&b, "| %s | %s |\n", escapeCell(name), escapeCell(s.Description))
		}
	}

	b.WriteString("\n### Built-in\n\n")
	b.WriteString("| Command | Description |\n|---------|-------------|\n")
	b.WriteString("| `/quit`, `/exit` | Exit ycode |\n")
	b.WriteString("| `/btw <query>` | Ask a side question without disturbing the current turn |\n")
	b.WriteString("| `/pause`, `/resume` | Pause or resume the running turn |\n")
	b.WriteString("| `!cmd`, `!!cmd` | Run a shell command; `!!` gives it the terminal |\n")

	b.WriteString("\n" + DocEndMarker + "\n")
	return b.String()
}

// escapeCell makes a value safe to place inside a markdown table cell.
func escapeCell(s string) string { return strings.ReplaceAll(s, "|", "\\|") }

// ReplaceDocSection rewrites the generated block between the markers, leaving
// the rest of the file untouched. Same contract as features.ReplaceSection:
// missing markers are an error, not a silent append.
func ReplaceDocSection(path, section string) (bool, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return false, fmt.Errorf("read %s: %w", path, err)
	}
	src := string(data)
	begin := strings.Index(src, DocBeginMarker)
	end := strings.Index(src, DocEndMarker)
	if begin < 0 || end < 0 {
		return false, fmt.Errorf("%s must contain both %s and %s", path, DocBeginMarker, DocEndMarker)
	}
	if end < begin {
		return false, fmt.Errorf("%s has the markers in the wrong order", path)
	}
	updated := src[:begin] + strings.TrimRight(section, "\n") + src[end+len(DocEndMarker):]
	if updated == src {
		return false, nil
	}
	return true, os.WriteFile(path, []byte(updated), 0o644)
}
