package weavesetup

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Config mirrors .ycode/loom.yaml. v1: hand-written tiny serializer
// (no yaml dep here) since the file is a handful of scalar fields and
// we don't want a transitive yaml pull on the substrate.
type Config struct {
	Slug              string
	DefaultBaseBranch string
	IdentityTier      string
	BackendMode       string
	DefaultTool       string
	LabelsCreated     bool
	HookInstalled     bool
	SetupComplete     bool
}

const configRelPath = ".ycode/loom.yaml"

// loadConfig reads .ycode/loom.yaml under hostCWD. Returns
// (zero-value, false, nil) when the file doesn't exist; (zero-value,
// false, err) only on read/parse failure of an existing file.
func loadConfig(hostCWD string) (Config, bool, error) {
	path := filepath.Join(hostCWD, configRelPath)
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return Config{}, false, nil
		}
		return Config{}, false, err
	}
	cfg, err := parseConfig(string(data))
	if err != nil {
		return Config{}, false, fmt.Errorf("parse %s: %w", path, err)
	}
	return cfg, true, nil
}

// saveConfig writes the config back to .ycode/loom.yaml, creating
// the directory if needed.
func saveConfig(hostCWD string, cfg Config) error {
	path := filepath.Join(hostCWD, configRelPath)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("mkdir .ycode: %w", err)
	}
	return os.WriteFile(path, []byte(renderConfig(cfg)), 0o644)
}

// renderConfig produces a stable YAML text. Order is fixed for
// deterministic output (the file is checked-into the user's repo
// via .gitignore guard upstream; deterministic ordering means clean
// diffs if a user opens it).
func renderConfig(c Config) string {
	var b strings.Builder
	b.WriteString("# ycode loom v2 — auto-generated by `ycode weave` first-run setup.\n")
	b.WriteString("# Safe to edit; subsequent weave commands honor overrides here.\n\n")
	fmt.Fprintf(&b, "slug: %s\n", c.Slug)
	fmt.Fprintf(&b, "default_base_branch: %s\n", c.DefaultBaseBranch)
	fmt.Fprintf(&b, "identity_tier: %s\n", c.IdentityTier)
	fmt.Fprintf(&b, "backend_mode: %s\n", c.BackendMode)
	fmt.Fprintf(&b, "default_tool: %s\n", c.DefaultTool)
	b.WriteString("\n# Setup-completion markers — do not edit by hand.\n")
	fmt.Fprintf(&b, "labels_created: %t\n", c.LabelsCreated)
	fmt.Fprintf(&b, "hook_installed: %t\n", c.HookInstalled)
	fmt.Fprintf(&b, "setup_complete: %t\n", c.SetupComplete)
	return b.String()
}

// parseConfig reads a tiny YAML subset (key: value, one per line).
// Comments and blank lines are skipped. Used by loadConfig.
func parseConfig(text string) (Config, error) {
	var c Config
	for ln, line := range strings.Split(text, "\n") {
		_ = ln
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		k, v, ok := strings.Cut(line, ":")
		if !ok {
			continue
		}
		k = strings.TrimSpace(k)
		v = strings.TrimSpace(v)
		switch k {
		case "slug":
			c.Slug = v
		case "default_base_branch":
			c.DefaultBaseBranch = v
		case "identity_tier":
			c.IdentityTier = v
		case "backend_mode":
			c.BackendMode = v
		case "default_tool":
			c.DefaultTool = v
		case "labels_created":
			c.LabelsCreated = v == "true"
		case "hook_installed":
			c.HookInstalled = v == "true"
		case "setup_complete":
			c.SetupComplete = v == "true"
		}
	}
	return c, nil
}
