database:
  file:
    folder: data
    extension: json

datasources:
  - name: prometheus
    default: true
    plugin:
      kind: PrometheusDatasource
      spec:
        proxy:
          kind: HTTPProxy
          spec:
            url: http://127.0.0.1:9090
