#!/usr/bin/env bash
# Generate a Homebrew formula for a ycode release. Reads SHA256SUMS from the
# release and emits Formula/ycode.rb to stdout.
#
# Usage: generate-homebrew-formula.sh <version> <sha256sums-file>
# Example: generate-homebrew-formula.sh 0.1.0 SHA256SUMS

set -euo pipefail

if [ $# -ne 2 ]; then
    echo "usage: $0 <version> <sha256sums-file>" >&2
    exit 2
fi

VERSION="$1"
SUMS="$2"

# Parse SHA256SUMS into a name → hash map. Missing platforms are tolerated;
# the formula simply omits the corresponding url/sha256 stanza.
sha_for() {
    local target="$1"
    awk -v target="$target" '
        $2 == "ycode-" target ".tar.gz" { print $1; found=1 }
        END { if (!found) exit 1 }
    ' "$SUMS"
}

# Try each known target; produce stanzas only for those present in SUMS.
darwin_arm64_sha=""
linux_amd64_sha=""

darwin_arm64_sha=$(sha_for darwin-arm64 2>/dev/null || true)
linux_amd64_sha=$(sha_for linux-amd64 2>/dev/null || true)

cat <<EOF
# frozen_string_literal: true

# Auto-generated by scripts/generate-homebrew-formula.sh on release v${VERSION}.
# Do not edit by hand — changes will be overwritten by the next release.

class Ycode < Formula
  desc "Pure Go CLI agent harness for autonomous software development"
  homepage "https://github.com/qiangli/ycode"
  version "${VERSION}"
  license "MIT"
EOF

if [ -n "$darwin_arm64_sha" ]; then
    cat <<EOF

  on_macos do
    on_arm do
      url "https://github.com/qiangli/ycode/releases/download/v#{version}/ycode-darwin-arm64.tar.gz"
      sha256 "${darwin_arm64_sha}"
    end
  end
EOF
fi

if [ -n "$linux_amd64_sha" ]; then
    cat <<EOF

  on_linux do
    on_intel do
      url "https://github.com/qiangli/ycode/releases/download/v#{version}/ycode-linux-amd64.tar.gz"
      sha256 "${linux_amd64_sha}"
    end
  end
EOF
fi

cat <<'EOF'

  def install
    bin.install "ycode"
  end

  test do
    output = shell_output("#{bin}/ycode version")
    assert_match "ycode #{version}", output
  end
end
EOF
