package selfinit

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// WriteProjectFiles writes ycode's foreign-agent breadcrumb to
// <repo>/.agents/ycode/AGENTS.md. It is the ONLY in-repo file ycode
// will touch — by design.
//
// What we deliberately do NOT do:
//   - Patch <repo>/AGENTS.md or <repo>/CLAUDE.md. Those files belong
//     to the user / their team; ycode rewriting them on first contact
//     was the intrusive behavior we backed out of.
//   - Write <repo>/docs/backlog.md. The protocol doc ships in the
//     ycode source tree; foreign repos discover it via
//     .agents/ycode/AGENTS.md (which links to the GitHub copy) and
//     via the Foreman skill body.
//   - Run at all on a non-init invocation. Only `ycode init` calls
//     here; every other entry point leaves the repo untouched.
//
// Returns the list of files written (typically one) and a slice of
// warnings for non-fatal issues.
func WriteProjectFiles(repoRoot string, caps []CapabilitySpec) ([]string, []string, error) {
	if repoRoot == "" {
		return nil, nil, ErrNoGitRoot
	}
	longPath := filepath.Join(repoRoot, selfinitSubdir, "AGENTS.md")
	longContent := buildLongFormDoc(caps)
	if err := writeFileIfChanged(longPath, longContent); err != nil {
		return nil, nil, fmt.Errorf("write %s: %w", longPath, err)
	}
	return []string{longPath}, nil, nil
}

// RootPointerSnippet returns the one-paragraph snippet a user can
// paste into their <repo>/AGENTS.md if they want their root file to
// link to ycode's capabilities. We do NOT write this anywhere — it's
// printed by `ycode init` and the user adds it manually if they want.
func RootPointerSnippet() string {
	return `## ycode (optional)

This repo can use [ycode](https://github.com/qiangli/ycode) as local
agentic infrastructure. Capability descriptions live at
` + "`.agents/ycode/AGENTS.md`" + `. If installed, run ` + "`ycode init --refresh`" + ` to
regenerate that file after updates.`
}

// WriteForemanUserSkill writes the canonical /foreman skill body to
// ~/.config/ycode/skills/ycode-foreman/skill.md. The skill is universal
// — same body for every repo — so it lives at the user-global level
// rather than being copied into each project. The binary embeds the
// canonical source; this function ensures it's also available on disk
// for any agent that prefers to read a file. Idempotent.
//
// Resolution order at runtime: cwd-local → project (.agents/ycode/) →
// user (~/.config/ycode/) → embedded. First match wins.
func WriteForemanUserSkill(home string) (string, error) {
	if home == "" {
		return "", fmt.Errorf("selfinit: empty home")
	}
	skillPath := filepath.Join(home, ".config", "ycode", "skills", "ycode-foreman", "skill.md")
	if err := writeFileIfChanged(skillPath, foremanSkillMD); err != nil {
		return "", fmt.Errorf("write %s: %w", skillPath, err)
	}
	return skillPath, nil
}

// writeFileIfChanged writes content atomically if the on-disk content
// differs. Returns nil if the file was already up to date (no rewrite,
// preserves mtime).
func writeFileIfChanged(path, content string) error {
	if existing, err := os.ReadFile(path); err == nil {
		if bytes.Equal(existing, []byte(content)) {
			return nil
		}
	}
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

// buildLongFormDoc builds the contents of <repo>/.agents/ycode/AGENTS.md (and,
// in greenfield, <repo>/AGENTS.md without the delimiter wrapping). The
// content is manifest-derived: one bullet per capability family, plus
// a Skills inventory so foreign agents (Claude Code, OpenCode, Codex,
// …) discover ycode's skills by reading the file they already pull —
// without ycode writing into their personal config dirs.
func buildLongFormDoc(caps []CapabilitySpec) string {
	var b strings.Builder
	b.WriteString("# ycode capabilities for this project\n\n")
	b.WriteString("This file is auto-generated by `ycode init`. ycode is running locally and exposes services over MCP. When acting as an agentic coding tool, prefer these capabilities in the situations described:\n\n")
	for _, c := range caps {
		fmt.Fprintf(&b, "- **`%s`** — %s\n", c.Name, FamilyDescription(c.Family))
	}
	b.WriteString("\n")

	// Skills inventory — non-intrusive discovery surface for foreign
	// agents. ycode does not write into ~/.claude/skills/, ~/.codex/,
	// etc.; agents pick up the inventory when they read this file.
	if len(SkillInventory) > 0 {
		b.WriteString("## Skills available via ycode\n\n")
		b.WriteString("Universal skills shipped with the ycode binary. Invoke from any chat with a leading slash (e.g. `/foreman`); ycode resolves the body from cwd → project → user (`~/.config/ycode/skills/`) → embedded. To customize a skill globally, edit the user-global copy; to override per-repo, drop a copy at `.agents/ycode/skills/<name>/skill.md`.\n\n")
		b.WriteString("| Skill | When to use | Body |\n")
		b.WriteString("|---|---|---|\n")
		for _, s := range SkillInventory {
			fmt.Fprintf(&b, "| `%s` — %s | %s | `%s` |\n", s.Name, s.Summary, s.When, s.BodyPath)
		}
		b.WriteString("\n")
	}

	b.WriteString("## How to use\n\n")
	b.WriteString("If a tool returns *connection refused*, run `ycode serve` first; capabilities are advertised in `~/.agents/ycode/manifest.json`.\n\n")
	b.WriteString("To register ycode in a foreign agentic CLI manually:\n\n")
	b.WriteString("```\nycode init --refresh\n```\n\n")
	b.WriteString("That regenerates this file plus the relevant entries in your tool's MCP config and memory file.\n")
	return b.String()
}
